export const PLANS = {
  Starter: {
    price: 9.99,
    maxProductTypes: 1,
    maxMonthlyOrders: 100,
    allowBackSurface: true,
    allowRemoveBg: true,
    removeBgMonthlyQuota: 100,
    aiImageMonthlyQuota: 70,
    maxShopTemplates: 0,
    allowProduction: false,
    allowGangSheet: false,
    features: {
      tr: [
        "1 ürün kategorisi",
        "100 sipariş/ay",
        "Ön + arka yüz baskı",
        "100 arka plan kaldırma/ay",
        "70 yapay zeka görseli/ay",
      ],
      en: [
        "1 product category",
        "100 orders/month",
        "Front + back surface print",
        "100 background removals/month",
        "70 AI images/month",
      ],
    },
  },
  Growth: {
    price: 19.99,
    maxProductTypes: 2,
    maxMonthlyOrders: 500,
    allowBackSurface: true,
    allowRemoveBg: true,
    removeBgMonthlyQuota: 500,
    aiImageMonthlyQuota: 200,
    maxShopTemplates: 10,
    allowProduction: false,
    allowGangSheet: false,
    features: {
      tr: [
        "2 ürün kategorisi",
        "500 sipariş/ay",
        "Ön + arka yüz baskı",
        "500 arka plan kaldırma/ay",
        "200 yapay zeka görseli/ay",
        "10 özel şablon",
      ],
      en: [
        "2 product categories",
        "500 orders/month",
        "Front + back surface print",
        "500 background removals/month",
        "200 AI images/month",
        "10 custom templates",
      ],
    },
  },
  Pro: {
    price: 49.99,
    maxProductTypes: 4,
    maxMonthlyOrders: 2000,
    allowBackSurface: true,
    allowRemoveBg: true,
    removeBgMonthlyQuota: 1500,
    aiImageMonthlyQuota: 600,
    maxShopTemplates: 20,
    allowProduction: true,
    allowGangSheet: true,
    features: {
      tr: [
        "4 ürün kategorisi",
        "2000 sipariş/ay",
        "Ön + arka yüz baskı",
        "1500 arka plan kaldırma/ay",
        "600 yapay zeka görseli/ay",
        "20 özel şablon",
        "Üretim & Gang Sheet",
        "Öncelikli destek",
      ],
      en: [
        "4 product categories",
        "2000 orders/month",
        "Front + back surface print",
        "1500 background removals/month",
        "600 AI images/month",
        "20 custom templates",
        "Production & Gang Sheet",
        "Priority support",
      ],
    },
  },
  Business: {
    price: 99.99,
    maxProductTypes: -1,
    maxMonthlyOrders: -1,
    allowBackSurface: true,
    allowRemoveBg: true,
    removeBgMonthlyQuota: 4000,
    aiImageMonthlyQuota: 1500,
    maxShopTemplates: -1,
    allowProduction: true,
    allowGangSheet: true,
    features: {
      tr: [
        "Sınırsız ürün kategorisi",
        "Sınırsız sipariş",
        "Ön + arka yüz baskı",
        "4000 arka plan kaldırma/ay",
        "1500 yapay zeka görseli/ay",
        "Sınırsız özel şablon",
        "Üretim & Gang Sheet",
        "Özel onboarding & destek",
      ],
      en: [
        "Unlimited product categories",
        "Unlimited orders",
        "Front + back surface print",
        "4000 background removals/month",
        "1500 AI images/month",
        "Unlimited custom templates",
        "Production & Gang Sheet",
        "Custom onboarding & support",
      ],
    },
  },
};

export type PlanKey = keyof typeof PLANS;

export const PLAN_NAMES = Object.keys(PLANS) as PlanKey[];
