name = "Bikafa Tisort Tasarim"
client_id = "ffb70fd5e03a3532fb1e47b3a8e9a052"
application_url = "https://threadlab-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_products,read_orders,write_app_proxy"

[auth]
redirect_urls = [
  "https://threadlab-production.up.railway.app/auth/callback",
  "https://threadlab-production.up.railway.app/auth/callback/offline"
]

[app_proxy]
url = "https://threadlab-production.up.railway.app/proxy"
prefix = "apps"
subpath = "tshirt-designer"
