# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1876054aac4bd32ba8019c2d27ef65f2"
name = "PrintLab"
application_url = "https://app.printlabapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = [
  "orders/delete",
  "orders/paid",
  "orders/fulfilled",
  "orders/cancelled",
  "orders/create"
]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_merchant_managed_fulfillment_orders,read_orders,read_products,write_app_proxy,write_cart_transforms,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://app.printlabapp.com/auth/callback",
  "https://app.printlabapp.com/auth/callback/offline"
]

[app_proxy]
url = "https://app.printlabapp.com/proxy"
subpath = "tshirt-designer"
prefix = "apps"
