name = "PrintLab"
client_id = "ffb70fd5e03a3532fb1e47b3a8e9a052"
application_url = "https://app.printlabapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/fulfilled"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/delete"]
uri = "/webhooks"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,write_fulfillments,write_app_proxy,write_cart_transforms,write_script_tags"

[auth]
redirect_urls = [
  "https://app.printlabapp.com/auth/callback",
  "https://app.printlabapp.com/auth/callback/offline"
]

[app_proxy]
url = "https://app.printlabapp.com/proxy"
prefix = "apps"
subpath = "tshirt-designer"
