api_version = "2025-07"

[[extensions]]
name = "Sipariş Tasarım Görüntüleyici"
handle = "order-design-viewer"
uid = "60160851-4263-ab07-055d-32622ecb4e289f7fc65a"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderDesignViewer.tsx"
target = "admin.order-details.block.render"
