api_version = "2025-07"

[[extensions]]
name = "Order Tracking Pixel"
handle = "order-tracking-pixel"
uid = "da112dce-0947-2e0e-f5b8-416f7ffb7a9bf8ab040a"
type = "web_pixel"
runtime_context = "strict"

[extensions.customer_privacy]
analytics = "enabled"
preferences = "disabled"
marketing = "disabled"
sale_of_data = "disabled"
